### ISSUE TITLE
working tracker logic

### ISSUE THREAD

**Issue by jahndan** [jahndan/nuzlocke-tracker#2]
tracker logic entails these:
- [x] location names (_high priority_)
- [ ] special handling of starter and catching tutorial
- [ ] keybinds to mark/skip/fail encounters (_high priority_)
  - [x] partially complete (still possible to break and get tracker in an invalid state)
  - [ ] full and proper handling of all edge cases
    - wild double battles end early because "wild X fainted" is captured on two frames
- [x] distinguish wild/foe pokemon (_high priority_)
- [x] per area tracking of species encounters in order (_high priority_)
- [ ] console output opposing pokemon info (_low priority_)
- [ ] dead/box/party status tracking (_medium priority_)
- [ ] gift pokemon dialogue? and replacing entries/tokens (_low priority_)
- [ ] badges, items? (_very low priority_)

more generally
- [x] determine precisely which characters are required for logic (as few as possible)
- [ ] etc

**Comment by jahndan** [comment]
@AitanSingh 
> The action should've been blocked before reaching the warning when to party then to box, and it let fail encounter all in the same encounter. In and out of battle, After trainer battle ended I added the final pokemon that I beat to party, failed encounter after trainer battle, all 3 actions can be marked outside of trainer battles

pasting this here because it should be resolved, but i'm most likely going to come up with better logic that (auto)tracks more unambiguously
